### ISSUE TITLE
Out of memory during the tracking

### ISSUE THREAD

**Issue by chenfsjz** [chaoma99/DSLT#7]
Hi, I try to run the tracker with vot-toolkit at the stack of vot2016 on matlab with an 1080ti GPU, when the tracker process the image 17 in the 'bag' sequence, there is an issue as below,

    @@TRAX:state 
    "334.8400,114.7000,380.6600,134.4600,332.7500,245.5600,286.9300,225.8100" 
    @@TRAX:frame "file:///home/vot2016/bag/00000018.jpg" 
    F0414 11:34:51.577589 19789 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 
    0)  out of memory

And when I run the demo code run_DSLT.m with the sequence in OTB_dataset, the tracker can produce the outcome normaly. It is just so strange!!

**Comment by carrierlxk** [comment]
The image patch size may be too large.
